---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 30
     27 df = pd.get_dummies(df, columns=['Season'], prefix='Season')
     29 # Train-Test Split: Train on first 80%, predict on last 20%
---> 30 mask = (df.index < df.index.quantile(0.8))
     31 df_train = df.loc[mask]
     32 df_test = df.loc[~mask]

AttributeError: 'DatetimeIndex' object has no attribute 'quantile'
