---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:433, in pandas._libs.tslibs.timedeltas.array_to_timedelta64()

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:465, in pandas._libs.tslibs.timedeltas._item_to_timedelta64_fastpath()

TypeError: Expected unicode, got datetime.time

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[25], line 10
      8 # First, ensure 'Date' and 'Hour' are in the right format
      9 df['Date'] = pd.to_datetime(df['Date'])
---> 10 df['Hour'] = pd.to_timedelta(df['Hour'], unit='h')
     12 # Combine 'Date' and 'Hour' into a new 'Datetime' column
     13 df['Datetime'] = df['Date'] + df['Hour']

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\tools\timedeltas.py:189, in to_timedelta(arg, unit, errors)
    187     return arg
    188 elif isinstance(arg, ABCSeries):
--> 189     values = _convert_listlike(arg._values, unit=unit, errors=errors)
    190     return arg._constructor(values, index=arg.index, name=arg.name)
    191 elif isinstance(arg, ABCIndex):

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\tools\timedeltas.py:242, in _convert_listlike(arg, unit, errors, name)
    239     arg = np.array(list(arg), dtype=object)
    241 try:
--> 242     td64arr = sequence_to_td64ns(arg, unit=unit, errors=errors, copy=False)[0]
    243 except ValueError:
    244     if errors == "ignore":

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\arrays\timedeltas.py:894, in sequence_to_td64ns(data, copy, unit, errors)
    891 # Convert whatever we have into timedelta64[ns] dtype
    892 if is_object_dtype(data.dtype) or is_string_dtype(data.dtype):
    893     # no need to make a copy, need to convert if string-dtyped
--> 894     data = _objects_to_td64ns(data, unit=unit, errors=errors)
    895     copy = False
    897 elif is_integer_dtype(data.dtype):
    898     # treat as multiples of the given unit

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\arrays\timedeltas.py:1004, in _objects_to_td64ns(data, unit, errors)
   1001 # coerce Index to np.ndarray, converting string-dtype if necessary
   1002 values = np.array(data, dtype=np.object_, copy=False)
-> 1004 result = array_to_timedelta64(values, unit=unit, errors=errors)
   1005 return result.view("timedelta64[ns]")

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:447, in pandas._libs.tslibs.timedeltas.array_to_timedelta64()

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:482, in pandas._libs.tslibs.timedeltas._item_to_timedelta64()

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:473, in pandas._libs.tslibs.timedeltas._item_to_timedelta64()

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:364, in pandas._libs.tslibs.timedeltas.convert_to_timedelta64()

ValueError: Invalid type for timedelta scalar: <class 'datetime.time'>

â€‹
